---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: dev
spec:
  selector:
    app: admin-server
  ports:
  - port: 9090
    targetPort: 9090
  type: ClusterIP



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: dev
spec:
  selector:
    matchLabels:
      app: admin-server
  replicas: 1
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - name: admin-server
        image: akerman0509/spring-petclinic-admin-server:ab3ec80
        ports:
        - containerPort: 9090
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
        #   requests:
        #     memory: "256Mi"
        #     cpu: "200m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9090
          initialDelaySeconds: 60
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9090
          initialDelaySeconds: 90
          periodSeconds: 10