---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
  namespace: dev
spec:
  selector:
    app: vets-service
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  namespace: dev
spec:
  selector:
    matchLabels:
      app: vets-service
  replicas: 1
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
      - name: vets-service
        image: akerman0509/spring-petclinic-vets-service:ab3ec80
        ports:
        - containerPort: 8083
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
        #   requests:
        #     memory: "256Mi"
        #     cpu: "200m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 90
          periodSeconds: 10