---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
  namespace: petclinic
spec:
  selector:
    app: visits-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
  namespace: petclinic
spec:
  selector:
    matchLabels:
      app: visits-service
  replicas: 1
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
      - name: visits-service
        image: akerman0509/spring-petclinic-visits-service:ab3ec80
        ports:
        - containerPort: 8082
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
        #   requests:
        #     memory: "256Mi"
        #     cpu: "200m"
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8082
        #   initialDelaySeconds: 60
        #   periodSeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8082
        #   initialDelaySeconds: 90
        #   periodSeconds: 10