---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: dev
spec:
  selector:
    app: customers-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  namespace: dev
spec:
  selector:
    matchLabels:
      app: customers-service
  replicas: 1
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      containers:
      - name: customers-service
        image: akerman0509/spring-petclinic-customers-service:ab3ec80
        ports:
        - containerPort: 8081
        env:
          - name: EUREKA_INSTANCE_HOSTNAME
            value: customers-service
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
        #   requests:
        #     memory: "256Mi"
        #     cpu: "200m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 90
          periodSeconds: 10