---
apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: dev
spec:
  selector:
    app: genai-service
  ports:
  - port: 8084
    targetPort: 8084
  type: ClusterIP

---
# GenAI Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
  namespace: dev
spec:
  selector:
    matchLabels:
      app: genai-service
  replicas: 1
  template:
    metadata:
      labels:
        app: genai-service
    spec:
      containers:
      - name: genai-service
        image: akerman0509/spring-petclinic-genai-service:ab3ec80
        ports:
        - containerPort: 8084
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
        #   requests:
        #     memory: "256Mi"
        #     cpu: "200m"
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: petclinic-secrets
              key: OPENAI_API_KEY
        - name: AZURE_OPENAI_KEY
          valueFrom:
            secretKeyRef:
              name: petclinic-secrets
              key: AZURE_OPENAI_KEY
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: petclinic-secrets
              key: AZURE_OPENAI_ENDPOINT
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 60
          periodSeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8084
        #   initialDelaySeconds: 90
        #   periodSeconds: 10